repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets
        language: system
        pass_filenames: false
      - id: maturin-gluex-rcdb-py
        name: maturin build gluex-rcdb-py
        entry: maturin develop --uv -r -m crates/gluex-rcdb-py/Cargo.toml
        language: system
        pass_filenames: false
      - id: maturin-gluex-ccdb-py
        name: maturin build gluex-ccdb-py
        entry: maturin develop --uv -r -m crates/gluex-ccdb-py/Cargo.toml
        language: system
        pass_filenames: false
      - id: maturin-gluex-lumi-py
        name: maturin build gluex-lumi-py
        entry: maturin develop --uv -r -m crates/gluex-lumi-py/Cargo.toml
        language: system
        pass_filenames: false
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        pass_filenames: false
      - id: ty
        name: ty
        entry: ty check
        language: system
        pass_filenames: false
  - repo: https://github.com/denehoffman/yamloom
    rev: yamloom-v0.5.0
    hooks:
      - id: yamloom-sync
        files: ^(\.github/workflows/.*\.ya?ml|\.yamloom\.py)$
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint
