---
name: Publish Workspace
"on":
  push:
    tags:
      - "*"
  workflow_dispatch: ~
concurrency:
  group: publish
  cancel-in-progress: false
jobs:
  release-workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Rust Tool
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-workspaces
      - run: cargo workspaces publish --from-git --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --yes